name: Test

on:
  push:
    tags-ignore:
      - v*
  pull_request:
    branches:

jobs:
  test:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        ts-version: [4.4.x, 4.5.x]
        react-version: ['16.9.0', 16.x, 17.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} & Typescript ${{ matrix.ts-version }} & React ${{ matrix.react-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn install
          yarn add typescript@${{ matrix.ts-version }} --dev
          yarn add react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} --dev
      - run: yarn test
      - name: Upload Coverage
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: coverage
          path: coverage
          if-no-files-found: error
          retention-days: 1
  coverage:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage
      - uses: codecov/codecov-action@v2
